Open Street Map: loading, analysing and visualising the Wikipedia of maps with R and other free tools
========================================================

## Introduction

Open Street Map is a crowd-sourced map of the world, the archetype of 'volunteered geographical information'
(Goodchild 2007). Putting the public in charge of editing the world's surface may seem like a risky 
business, given that cartographers have specialist skills developed over centuries. Yet the emergence 
of high resolution aerial photography covering the entirety of the Earth's surface and the 
explosion in GPS ownership via smartphones has enabled citizens to become accurate sensors of the world, 
with the added advantage that they are likely to know their local areas far better than any cartographer.

Of course there are teething issues with any large-scale open source database, including variable data quality, 
patchy and incomplete coverage and inconsistencies from place to place (Haklay 2010). Yet all of these
issues are gradually being out. The advantages of Open Street Map outweight these downsides for
many applications *already*. These include:

- Rapid updates of new projects
- Greater range of attributes (e.g. shop names)
- Ability to share data with anyone without breaching license

In additions there are a number of ethical benefits of using OSM: it's community
a map for the greater good ([Wroclawski 2014](http://www.theguardian.com/technology/2014/jan/14/why-the-world-needs-openstreetmap)).

## Getting the data

## Spatial subsetting

## Attribution selection

## Analysis and visualisation with R

## Further resources

